# oh-my-pi — OMP, "a coding agent with the IDE wired in" (fork of Pi)
#
# Upstream publishes a single self-contained binary per platform on GitHub
# releases: a Bun --compile executable named `omp` (with the pi_natives Rust
# addons embedded). The glibc Linux builds only link libc/ld-linux/libpthread/
# libdl/libm, so autoPatchelfHook is enough on NixOS; the embedded speaker
# dlopens libpulse/libasound at runtime, hence the LD_LIBRARY_PATH wrapper.
# Version + per-platform hashes live in sources.json and are regenerated by
# passthru.updateScript, which follows the latest GitHub release.
{
  lib,
  stdenv,
  fetchurl,
  writeShellScriptBin,
  python3,
  git,
  autoPatchelfHook,
  makeWrapper,
  libpulseaudio,
  alsa-lib,
  versionCheckHook,
  writableTmpDirAsHomeHook,
}: let
  sources = lib.importJSON ./sources.json;
  inherit (sources) version;
  current = sources.platforms.${stdenv.hostPlatform.system};
in
  stdenv.mkDerivation {
    pname = "oh-my-pi";
    inherit version;

    src = fetchurl {
      url = "https://github.com/can1357/oh-my-pi/releases/download/v${version}/${current.asset}";
      hash = current.hash;
    };

    nativeBuildInputs =
      lib.optionals stdenv.hostPlatform.isLinux [autoPatchelfHook makeWrapper];

    dontUnpack = true;
    # Bun --compile binaries are already set up upstream; re-stripping risks
    # corrupting the embedded runtime and native addons.
    dontStrip = true;

    # The embedded pi_natives speaker dlopens libpulse-simple.so.0 (PulseAudio)
    # and libasound.so.2 (ALSA) at runtime. These are not in DT_NEEDED (no
    # .note.dlopen section either), so autoPatchelfHook cannot patch them in;
    # the postFixup wrapper below exports them through LD_LIBRARY_PATH.

    # Release assets are raw executables (no archive wrapper).
    installPhase = ''
      runHook preInstall

      mkdir -p $out/bin
      install -Dm755 $src $out/bin/omp

      runHook postInstall
    '';

    postFixup = lib.optionalString stdenv.hostPlatform.isLinux ''
      wrapProgram $out/bin/omp \
        --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [libpulseaudio alsa-lib]}
    '';

    nativeInstallCheckInputs = [
      versionCheckHook
      writableTmpDirAsHomeHook
    ];
    doInstallCheck = true;
    versionCheckProgram = "${placeholder "out"}/bin/omp";
    versionCheckProgramArg = "--version";

    passthru.updateScript = writeShellScriptBin "update-oh-my-pi" ''
      set -euo pipefail
      ${lib.getExe git} rev-parse --show-toplevel >/dev/null
      exec ${lib.getExe python3} ${./update.py} "$(${lib.getExe git} rev-parse --show-toplevel)/pkgs/oh-my-pi/sources.json"
    '';

    meta = {
      description = "Terminal-based coding agent with the IDE wired in (fork of Pi)";
      homepage = "https://omp.sh";
      downloadPage = "https://github.com/can1357/oh-my-pi/releases";
      changelog = "https://github.com/can1357/oh-my-pi/blob/main/packages/coding-agent/CHANGELOG.md";
      license = lib.licenses.mit;
      maintainers = [
        {
          name = "Guillaume ASSIER";
          github = "GuillaumeASSIER";
        }
      ];
      sourceProvenance = with lib.sourceTypes; [binaryNativeCode];
      platforms = builtins.attrNames sources.platforms;
      mainProgram = "omp";
    };
  }
