# msgvault — local-first archive for email, chat, meetings, and contacts.
#
# Upstream publishes prebuilt release archives per platform: a stripped Go
# binary with CGO native code (mattn/go-sqlite3 with FTS5 and DuckDB for
# Parquet analytics) and the Svelte Web UI embedded. The glibc Linux builds
# link libm/libstdc++/libgcc_s/libc only, so autoPatchelfHook is enough on
# NixOS. Version + per-platform hashes live in sources.json and are
# regenerated by passthru.updateScript, which follows the latest GitHub
# release.
{
  lib,
  stdenv,
  fetchurl,
  writeShellScriptBin,
  python3,
  git,
  autoPatchelfHook,
  libgcc,
  versionCheckHook,
  writableTmpDirAsHomeHook,
}: let
  sources = lib.importJSON ./sources.json;
  inherit (sources) version;
  current = sources.platforms.${stdenv.hostPlatform.system};
in
  stdenv.mkDerivation {
    pname = "msgvault";
    inherit version;

    src = fetchurl {
      url = "https://github.com/kenn-io/msgvault/releases/download/v${version}/${current.asset}";
      hash = current.hash;
    };

    # The archive contains a bare binary at its root, no wrapper directory.
    sourceRoot = ".";

    nativeBuildInputs =
      lib.optionals stdenv.hostPlatform.isLinux [autoPatchelfHook];

    # The CGO build (DuckDB C++ analytics, go-sqlite3) links libstdc++.so.6
    # and libgcc_s.so.1 in addition to glibc.
    buildInputs = lib.optionals stdenv.hostPlatform.isLinux [
      libgcc
      stdenv.cc.cc.lib
    ];

    # Release binary is already stripped upstream; re-stripping a Go binary
    # risks corrupting it.
    dontStrip = true;

    installPhase = ''
      runHook preInstall

      install -Dm755 msgvault $out/bin/msgvault

      runHook postInstall
    '';

    # Any msgvault command creates ~/.msgvault, so the version check needs a
    # writable HOME.
    nativeInstallCheckInputs = [
      versionCheckHook
      writableTmpDirAsHomeHook
    ];
    doInstallCheck = true;
    versionCheckProgramArg = "version";

    passthru.updateScript = writeShellScriptBin "update-msgvault" ''
      set -euo pipefail
      ${lib.getExe git} rev-parse --show-toplevel >/dev/null
      exec ${lib.getExe python3} ${./update.py} "$(${lib.getExe git} rev-parse --show-toplevel)/pkgs/msgvault/sources.json"
    '';

    meta = {
      description = "Local-first archive for email, chat, meetings, and contacts with offline search and AI access";
      longDescription = ''
        msgvault brings email, chat, meetings, calendar, and contacts into a
        single local archive (SQLite + DuckDB/Parquet) on your own hardware.
        It offers keyword and semantic search, relationship analytics, and a
        CLI, TUI, Web UI, HTTP API, and MCP server for AI assistants.
      '';
      homepage = "https://www.msgvault.io/";
      downloadPage = "https://github.com/kenn-io/msgvault/releases";
      changelog = "https://github.com/kenn-io/msgvault/blob/main/docs/changelog.md";
      license = lib.licenses.mit;
      maintainers = [
        {
          name = "Guillaume ASSIER";
          github = "GuillaumeASSIER";
        }
      ];
      sourceProvenance = with lib.sourceTypes; [binaryNativeCode];
      platforms = builtins.attrNames sources.platforms;
      mainProgram = "msgvault";
    };
  }
