# opencode2 — OpenCode 2.0 preview (@opencode-ai/cli "next" dist-tag)
#
# The upstream npm package is split into a tiny launcher (@opencode-ai/cli)
# and per-platform binary packages (@opencode-ai/cli-<os>-<arch>). We skip the
# launcher entirely and fetch only the platform tarball that matches the build
# system: it contains a self-contained Bun --compile executable (opencode2)
# that needs nothing but glibc at runtime.
#
# Version + per-platform hashes live in sources.json and are regenerated by
# passthru.updateScript, which follows the npm "next" dist-tag (the default
# nix-update-script would track "latest", i.e. the v1 line, which is wrong).
{
  lib,
  stdenv,
  fetchurl,
  writeShellScriptBin,
  python3,
  git,
  autoPatchelfHook,
  installShellFiles,
  versionCheckHook,
  writableTmpDirAsHomeHook,
}: let
  sources = lib.importJSON ./sources.json;
  inherit (sources) version;
  current = sources.platforms.${stdenv.hostPlatform.system};
in
  stdenv.mkDerivation {
    pname = "opencode";
    inherit version;

    src = fetchurl {
      url = "https://registry.npmjs.org/@opencode-ai/cli-${current.npm}/-/cli-${current.npm}-${version}.tgz";
      hash = current.hash;
    };

    nativeBuildInputs =
      [
        installShellFiles
      ]
      ++ lib.optionals stdenv.hostPlatform.isLinux [autoPatchelfHook];

    dontUnpack = true;
    # Bun --compile binaries are already stripped upstream; re-stripping risks
    # corrupting the embedded runtime.
    dontStrip = true;

    installPhase = ''
      runHook preInstall

      tar -xzf $src package/bin/opencode2
      install -Dm755 package/bin/opencode2 $out/bin/opencode2

      runHook postInstall
    '';

    # postFixup (the attribute) runs *before* the autoPatchelfHook array hook,
    # so the binary isn't patched yet there. installCheckPhase runs after
    # fixupPhase (and after versionCheckHook proves the binary exec's), so it
    # is the earliest safe place to run the patched binary for completions.
    postInstallCheck = lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
      installShellCompletion --cmd opencode2 \
        --bash <($out/bin/opencode2 --completions bash) \
        --zsh <($out/bin/opencode2 --completions zsh) \
        --fish <($out/bin/opencode2 --completions fish)
    '';

    nativeInstallCheckInputs = [
      versionCheckHook
      writableTmpDirAsHomeHook
    ];
    doInstallCheck = true;
    versionCheckProgram = "${placeholder "out"}/bin/opencode2";
    versionCheckProgramArg = "--version";

    passthru.updateScript = writeShellScriptBin "update-opencode" ''
      set -euo pipefail
      ${lib.getExe git} rev-parse --show-toplevel >/dev/null
      exec ${lib.getExe python3} ${./update.py} "$(${lib.getExe git} rev-parse --show-toplevel)/pkgs/opencode/sources.json"
    '';

    meta = {
      description = "OpenCode 2.0 preview - AI coding agent command line interface";
      homepage = "https://github.com/anomalyco/opencode";
      downloadPage = "https://www.npmjs.com/package/@opencode-ai/cli";
      license = lib.licenses.mit;
      maintainers = [
        {
          name = "Guillaume ASSIER";
          github = "GuillaumeASSIER";
        }
      ];
      sourceProvenance = with lib.sourceTypes; [binaryNativeCode];
      platforms = builtins.attrNames sources.platforms;
      mainProgram = "opencode2";
    };
  }
