# opencode — OpenCode stable line (latest GitHub release of anomalyco/opencode)
#
# Upstream publishes prebuilt CLI archives on GitHub releases: the binary is a
# self-contained Bun --compile executable named `opencode` that needs nothing
# but glibc at runtime. Linux ships as .tar.gz, macOS as .zip, each containing
# the single `opencode` binary.
#
# Version + per-platform hashes live in sources.json and are regenerated by
# passthru.updateScript, which follows the latest GitHub release (the stable
# v1 line). Note: the npm "next"/"latest" dist-tags of @opencode-ai/cli both
# track the OpenCode 2.0 preview line instead (binaries `opencode2`/`lildax`),
# which is why we fetch the GitHub release archives directly.
{
  lib,
  stdenv,
  fetchurl,
  writeShellScriptBin,
  python3,
  git,
  unzip,
  autoPatchelfHook,
  installShellFiles,
  versionCheckHook,
  writableTmpDirAsHomeHook,
}: let
  sources = lib.importJSON ./sources.json;
  inherit (sources) version;
  current = sources.platforms.${stdenv.hostPlatform.system};
in
  stdenv.mkDerivation {
    pname = "opencode";
    inherit version;

    src = fetchurl {
      url = "https://github.com/anomalyco/opencode/releases/download/v${version}/${current.asset}";
      hash = current.hash;
    };

    nativeBuildInputs =
      [
        installShellFiles
      ]
      ++ lib.optionals stdenv.hostPlatform.isLinux [autoPatchelfHook]
      ++ lib.optionals stdenv.hostPlatform.isDarwin [unzip];

    dontUnpack = true;
    # Bun --compile binaries are already stripped upstream; re-stripping risks
    # corrupting the embedded runtime.
    dontStrip = true;

    # Each archive holds a single `opencode` executable at its root. Extract
    # into a subdirectory: leaving a bare `opencode` file in the build cwd (the
    # sandbox $TMPDIR, e.g. /build) would clash with the $TMPDIR/opencode dir
    # the binary mkdir's at startup (Bun EEXIST).
    installPhase = ''
      runHook preInstall

      mkdir -p extract-dir
      ${
        if stdenv.hostPlatform.isDarwin
        then "unzip -o $src -d extract-dir"
        else "tar -xzf $src -C extract-dir"
      }
      mkdir -p $out/bin
      install -Dm755 extract-dir/opencode $out/bin/opencode

      runHook postInstall
    '';

    # postFixup (the attribute) runs *before* the autoPatchelfHook array hook,
    # so the binary isn't patched yet there. installCheckPhase runs after
    # fixupPhase (and after versionCheckHook proves the binary exec's), so it
    # is the earliest safe place to run the patched binary for completions.
    postInstallCheck = lib.optionalString (stdenv.buildPlatform.canExecute stdenv.hostPlatform) ''
      installShellCompletion --cmd opencode \
        --bash <($out/bin/opencode completion) \
        --zsh <(SHELL=/bin/zsh $out/bin/opencode completion)
    '';

    nativeInstallCheckInputs = [
      versionCheckHook
      writableTmpDirAsHomeHook
    ];
    doInstallCheck = true;
    versionCheckProgram = "${placeholder "out"}/bin/opencode";
    versionCheckProgramArg = "--version";

    passthru.updateScript = writeShellScriptBin "update-opencode" ''
      set -euo pipefail
      ${lib.getExe git} rev-parse --show-toplevel >/dev/null
      exec ${lib.getExe python3} ${./update.py} "$(${lib.getExe git} rev-parse --show-toplevel)/pkgs/opencode/sources.json"
    '';

    meta = {
      description = "AI coding agent command line interface";
      homepage = "https://github.com/anomalyco/opencode";
      downloadPage = "https://github.com/anomalyco/opencode/releases";
      license = lib.licenses.mit;
      maintainers = [
        {
          name = "Guillaume ASSIER";
          github = "GuillaumeASSIER";
        }
      ];
      sourceProvenance = with lib.sourceTypes; [binaryNativeCode];
      platforms = builtins.attrNames sources.platforms;
      mainProgram = "opencode";
    };
  }
